base_url = "https://jel1yspot.github.io/zola-blog"
title = "A normal blog"
description = "啫喱有一个 blog"
default_language = "zh"
author = "jel1yspot"
theme = "terminus"

[markdown]
render_emoji = true
external_links_target_blank = true
github_alerts = true
